name: LeetCode Metrics
on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:
  push: {branches: [main]}

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: leetcode-stats.svg
          token: ${{ secrets.REPO_METRICS }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: "axstiz"
          plugin_leetcode_sections: solved, skills
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
